### ISSUE TITLE
The Broccoli Plugin: [Funnel: Funnel (testLoader)] failed

### ISSUE THREAD

**Issue by mcm-ham** [ember-cli/ember-cli-test-loader#24]
I get the following error on Windows with 1.0.0 and 1.1.0, it works fine with 0.2.2. It may be related to https://github.com/broccolijs/broccoli-funnel/issues/53

```
The Broccoli Plugin: [Funnel: Funnel (testLoader)] failed with:
Error: ENOENT: no such file or directory, lstat 'E:\Michael\Workspace\stock.goodcity\bower_components\ember-cli-test-loader\test-loader.js'
  at Error (native)
  at Object.fs.lstatSync (fs.js:839:18)
  at Object.realpathSync (fs.js:1439:21)
  at symlinkWindows (E:\Michael\Workspace\stock.goodcity\node_modules\symlink-or-copy\index.js:87:26)
  at Function.symlinkOrCopySync [as sync] (E:\Michael\Workspace\stock.goodcity\node_modules\symlink-or-copy\index.js:56:5)
  at Funnel._copy (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:398:19)
  at Funnel.processFile (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:381:8)
  at Funnel.applyPatch [as _applyPatch] (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:298:12)
  at Funnel.<anonymous> (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:250:10)
  at Array.forEach (native)
  at Funnel.processFilters (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:249:9)
  at Funnel.build (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:172:10)
  at E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-plugin\read_compat.js:61:34
  at lib$rsvp$$internal$$tryCatch (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:476:11)
  at lib$rsvp$asap$$flush (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:1198:9)
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)


The broccoli plugin was instantiated at:
  at Funnel.Plugin (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-plugin\index.js:7:31)
  at new Funnel (E:\Michael\Workspace\stock.goodcity\node_modules\broccoli-funnel\index.js:44:10)
  at EmberApp.testFiles (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\broccoli\ember-app.js:1367:20)
  at EmberApp.test (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\broccoli\ember-app.js:1073:28)
  at EmberApp.toArray (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\broccoli\ember-app.js:1571:61)
  at EmberApp.toTree (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\broccoli\ember-app.js:1586:30)
  at module.exports (E:\Michael\Workspace\stock.goodcity\ember-cli-build.js:32:14)
  at Class.module.exports.Task.extend.setupBroccoliBuilder (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\models\builder.js:55:19)
  at Class.module.exports.Task.extend.init (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\models\builder.js:89:10)
  at new Class (E:\Michael\Workspace\stock.goodcity\node_modules\core-object\core-object.js:18:12)
  at Class.module.exports.Task.extend.run (E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\tasks\serve.js:15:19)
  at E:\Michael\Workspace\stock.goodcity\node_modules\ember-cli\lib\commands\serve.js:64:24
  at lib$rsvp$$internal$$tryCatch (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:493:16)
  at lib$rsvp$$internal$$invokeCallback (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:505:17)
  at lib$rsvp$$internal$$publish (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:476:11)
  at lib$rsvp$asap$$flush (E:\Michael\Workspace\stock.goodcity\node_modules\rsvp\dist\rsvp.js:1198:9)
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

**Comment by clekstro** [comment]
I get this locally on a Mac as well while trying to bump the version on the Travis web client to `1.1.0`. I created a [branch](https://github.com/travis-ci/travis-web/tree/test-loader-woes) to help reproduce and [here](https://travis-ci.org/travis-ci/travis-web/builds/126499641) is the broken Travis build showing a similar stacktrace.

So this doesn't appear to be OS-specific.

**Comment by erichonkanen** [comment]
+1 im getting this

**Comment by trentmwillis** [comment]
As of `1.0.0`, `ember-cli-test-loader` is now an NPM module instead of a Bower package. Unfortunately, Ember-CLI currently assumes that `ember-cli-test-loader` is a Bower package, which is why you see the error you are seeing.

A [fix has been submitted](https://github.com/ember-cli/ember-cli/pull/5709) and should be available for use in the next Ember-CLI release.

**Comment by rwjblue** [comment]
Right, basically, use 0.2.x until you upgrade to ember-cli@2.7 or later

**Comment by clekstro** [comment]
Cool, thanks for the clarification. Can #20 be merged then so others don't hit this?

**Comment by renatocarvalho** [comment]
I am using `ember-cli@2.7`, added `ember-cli-test-loader` as an NPM module and removed the Bower package. I'm still seeing this error.

**Comment by renatocarvalho** [comment]
Just found out that [ember-cli-blanket](https://github.com/sglanzer/ember-cli-blanket) we one that was breaking the app. I removed it and it's working again.

**Comment by v3ss0n** [comment]
I am getting this error , not sure it is same. 
```
The Broccoli Plugin: [Funnel: Funnel (test index)] failed with:
Error: ENOENT: no such file or directory,
```

But i do not have ember-cli-blanket . it happesn out of the blue. only redemy is deleting whole app and rebuilding from scratch.

**Comment by downzer0** [comment]
Delete the `tests` folder that's automatically created on build. That fixed it for me. And you can always regenerate if you use the tests.

**Comment by v3ss0n** [comment]
@downzer0  thanks a lot , i will try!

**Comment by VSG24** [comment]
@downzer0 That worked for me as well.
