### ISSUE TITLE
errror of me

### ISSUE THREAD

**Issue by phonglanpls** [ember-cli/ember-cli-test-loader#27]
Caught exception:
```
 Error: ENOENT: no such file or directory, lstat 'C:\a2\proj\typings\mai
    at Error (native)
    at Object.fs.lstatSync (fs.js:839:18)
    at Object.realpathSync (fs.js:1439:21)
    at C:\a2\proj\node_modules\ionic-gulp-browserify-typescript\node_mod
fy\index.js:58:38
    at Array.map (native)
    at DestroyableTransform.flush [as _flush](C:a2projnode_modulesi
p-browserify-typescriptnode_modulestsifyindex.js:58:6)
    at DestroyableTransform.<anonymous> (C:\a2\proj\node_modules\ionic-g
serify-typescript\node_modules\tsify\node_modules\through2\node_modules\
-stream\lib_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
```
Mind letting us know? https://github.com/driftyco/ionic-cli/issues

**Comment by Turbo87** [comment]
@phonglanpls I don't see how that exception is relevant to this project?! 🤔
